version: '3.8'

services:
  lens:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - lens-view-network

networks:
  lens-view-network:
    name: lens-view-network
