name: Build and Push Docker to EKS

on:
  push:
    branches:
      - eks

jobs:                                            
  release:                                       
    name: Release                                
    runs-on: ubuntu-latest         
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_REPOSITORY: murky-manager-app
      DOCKER_TAG: dev
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/murky-manager-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "NEXT_PUBLIC_DB_HOST=http://view.cursetheweb.online" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .

      # - name: Push Docker image
      #   run: |
      #     docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create kubeconfig file
        run: echo "${{ secrets.KUBE_CONFIG_DATA }}" > ${{ github.workspace }}/kubeconfig

      - name: Checkout Helm Chart Repository
        uses: actions/checkout@v2
        with:
          repository: DarkMurky/murky-view-infrasturcture

      - name: Print Directory
        run: |
          echo "Listing contents of the directory:"
          ls -a

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Deploy with Helm
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          helm upgrade --install my-release ./k8s/murky-view-chart
