name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Create .env file
      #   run: echo "NEXT_PUBLIC_DB_HOST=http://localhost" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t kvait/murky-manager-app:dev .

      - name: List files after build
        run: |
          echo "Listing files in the current directory:"
          ls -al

      - name: Print .env
        run: |
          echo "Printin env:"
          cat .env

      - name: Push Docker image
        run: |
          docker push kvait/murky-manager-app:dev
