name: Build and Push Docker to EKS

on:
  push:
    branches:
      - terraform

jobs:                                            
  build:                                       
    name: Release                                
    runs-on: ubuntu-latest         
    env:
      ENVIRONMENT: dev
      HELM_RELEASE_NAME: ${{ secrets.ENVIRONMENT }}-lens-view
      AWS_EKS_CLUSTER_NAME: ${{ secrets.ENVIRONMENT }}-${{ secrets.AWS_EKS_CLUSTER_NAME }}

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout Helm chart repository
        uses: actions/checkout@v2
        with:
          repository: DarkMurky/murky-view-infrasturcture

      # - name: Check if s3 bucket exists
      #   working-directory: ./scripts
      #   run: |
      #     chmod +x ./validate_s3_bucket.sh
      #     ./validate_s3_bucket.sh

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #       terraform_version: 1.10.4

      # - name: Terraform init and validate
      #   working-directory: ./k8s/terraform
      #   run: |
      #     terraform init -backend-config="key=state/${{ env.ENVIRONMENT }}/terraform.tfstate"

      # - name: Terraform plan
      #   working-directory: ./k8s/terraform
      #   run: |
      #     terraform plan

      # - uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ secrets.TOKEN_GITHUB }}
      #     approvers: DarkMurky
      #     minimum-approvals: 1
      #     issue-title: "Deploying to ${{ env.ENVIRONMENT }}"
      #     issue-body: "Review the terraform plan"
      #     exclude-workflow-initiator-as-approver: false

      # - name: Terraform apply
      #   working-directory: ./k8s/terraform
      #   run: |
      #     terraform apply -auto-approve -var="environment=${{ env.ENVIRONMENT }}"

      - name: Debug AWS EKS Cluster Name
        run: echo "AWS EKS Cluster Name: ${{ env.AWS_EKS_CLUSTER_NAME }}"

      - name: Update kubeconfig context
        run: |
          aws eks update-kubeconfig --name ${{ env.AWS_EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Get pods
        run: |
           kubectl get pods --all-namespaces

      - name: Create secrets file
        working-directory: ./k8s/murky-view-chart
        run: |
          echo "db-user: ${{ secrets.DATABASE_USER}}" > secrets
          echo "db-pass: ${{ secrets.DATABASE_PASSWORD }}" >> secrets

      - name: Deploy with Helm
        run: |
          kubectl get ns ${{ env.ENVIRONMENT }} || kubectl create ns ${{ env.ENVIRONMENT }}
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./k8s/murky-view-chart -f ./k8s/murky-view-chart/values-${{ env.ENVIRONMENT }}.yml
