name: Build and Push Docker to EKS

on:
  push:
    branches:
      - terraform

jobs:                                            
  build:                                       
    name: Release                                
    runs-on: ubuntu-latest         
    env:
      DEV_AWS_EKS_CLUSTER_NAME: ${{ secrets.DEV_AWS_EKS_CLUSTER_NAME }}

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.10.4

      - name: Checkout Helm chart repository
        uses: actions/checkout@v2
        with:
          repository: DarkMurky/murky-view-infrasturcture

      # - name: Terraform init and validate
      #   working-directory: ./k8s/terraform
      #   run: |
      #     terraform init

      # - name: Terraform plan
      #   working-directory: ./k8s/terraform
      #   run: |
      #     terraform plan

      # - uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ secrets.TOKEN_GITHUB }}
      #     approvers: DarkMurky
      #     minimum-approvals: 1
      #     issue-title: "Deploying to dev"
      #     issue-body: "Review the terraform plan"
      #     exclude-workflow-initiator-as-approver: false

      # - name: Terraform apply
      #   working-directory: ./k8s/terraform
      #   run: |
      #     terraform apply -auto-approve

      - name: Update kubeconfig context
        run: |
          aws eks update-kubeconfig --name ${{ env.DEV_AWS_EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Get pods
        run: |
           kubectl create namespace dev

      - name: Get pods
        run: |
           kubectl get pods --all-namespaces

      - name: Create secrets file
        run: |
          echo "db-user: ${{ secrets.DATABASE_USER}}" > secrets.txt
          echo "db-pass: ${{ secrets.DATABASE_PASSWORD }}" >> secrets.txt

      - name: Deploy with Helm
        run: |
          helm upgrade --install dev-lens-view ./k8s/murky-view-chart -f ./k8s/murky-view-chart/values-dev.yml
